language: objective-c
osx_image: xcode10.1

addons:
  sonarcloud:
    organization: "guhungry-github"
    token:
      secure: "V1IcT0FbkhgzfBl6Bg+53DJdz8HYENpI2pwLuZLkzn1qB37ouia31o2ob+X4ElfXKwRNfJ1rm00i5BcVfiSRn6q84vgvHckBnvj/tTkGEvkv7r5oWgIYSehuh1i0FpGty5CspSsimiWkQtQFt8aDX9IkZEosN8aihOYqlVUrCUjtPs82t3OQCZJrQKclKglqRIrFGM8wAWYRlpLiC+m1mC/TbMgsOOSHlvx/s15D6U2OcS3SePWXq3O7K+OgJauf8y9YVPJ20VZ5OknNWlmpThPk6p+P6W0V3JknRtrCCcqku/+Zt/30utxIrt5buBxEOXqICjVXAeiCOBixe0+nqzmiKQScUhijANXLhDHOXen4qMjFv1paoWWM8pewJIITYKBB4bHOz0PvkM9O26n7BPcwkKR3oierj0zM0R4khY1lzePgn7eh1wxsVbLV/y/LUeHYp4DjBftqpwVaNn4Ch5lh/IQZPHpZqp8W3hueupzfKA+sxgKtu9sJ4jSG8S5JfFAC/pH0WbMb6QlpCf4R/0JBFfKd7ry+7qut7yHnb4fxXELKZ01GdVeNmOlQZix7UPgefOqCi3LWMhSJbUCtY0tvxq3LoRCsHm9Gph1ilCNvTFGAkxPJETSHlJSMPj/uUYSIuDy3vYPsjJl6C01yH4qQXQcCeA8Ph9xn5Z36kig="

before_install:
  - env
  - locale
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem update cocoapods --no-rdoc --no-ri --no-document --quiet
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - ci/buildViaTravis.sh
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: "auUu13pwYmbprBP7RvN1WqL01yBaN0l9YFSfV31U8MameHFSrLD+F1kmz2EUz3SAdEYNzsGT0eAPVXZMC1fSGnQx60QVuInX+58g3O4egyIk9M1eRhMTDTqelpyIOLR31b5RT4aueszOjZdoqjYSmtTwiigBHvgOFODKOW0OeJY+HylIq60rMV1udFnhFpYNWALX1uw5O3x9FZx9gzQhKuTxzwp+396ldiIYglpfM+vzXHQXDpCEGMY7SPtvx9NOvmDTvv/TEYxsS6c3hdIY8FheuqYHW0agnAHO/Hj7x9nB4b8tqb+vuTyiI6wZDFqJUhE3lpKySwuY7cjK/tGn+BLPxV721ZfnTUIxtR/OUHZCLos8Yahkfe5COK/DhqpTxLow7+qL3ZlPpV0Sj7R6JZxdWUCJIKYzT9BlzIk+hDuGcNTbn2cPnkQHqKug3YiXHA84gSN/h3mm+dEy1fgjogC2p09DROVFJN8IuL/rgeHNZyB3eTk6aJPCJbXcNSFF/Q6lwg9tpDzQQHjm3jN1/WDUzxILWith7D5AtBXaDl8qptHSr4QiTDjkIMjLUwS73svKKWNGfMG3a1rSssbu/iCiNxUeAMgYBzhk3X3Eki6z6Aw/gWX4HK7oqDgu/RqAIkVda63438Q4PRmNAzwrKyM2KJIuMRxE8NWTFgN/QEg="
