language: objective-c
osx_image: xcode10

addons:
  sonarcloud:
    organization: "guhungry-github"
    token:
      secure: "AQFFsLB8ZRtFo/zdfGrMWYHloilB1mU7jlJRVR0AnPxv/zH+q2ozZ0K0UEcRu7PJT2X0T386bsVLlfeXMZo4bHwdCqpVgqFo3PpQ+w51eW2vPdEAS2Hrj7h301YZQ1/AWrZaBsAn2XTJKvpZEprvQdTqQ/25pJz+udPyaigCifywB9EmoWDn3evEnYCW+ks90rGys/+Lwsaq35TmiUwetlAjUqgvpuM2pjJDxAW9Tyvdhbwqkh3aJFYELDOcCLkWzvq6F/NxVj5ssAbkHFJ6EMc38LS+nsNQmLv6ReaZxBNYAtiMDu/Ws3DfE0Wd/3KWovzkkF6ljs7tVjIu99mUgSBCLw1fuPgGie1y/DD0s0bqCk2gpbzJEOLveB30QF4/NslbTBE/mLhPe8H21Q42hm0WKuYewzVLy1M9HdICLE5imyO2rELRMzH99iG2/qr7qIBokgZ8lDCPYJIJ/zSi+6FaG5gl6b1JdFWJLPaPTomlgu6zmblddfyzDW/p0Z6fVJvdfhj6pU9U/q1U79eqIN9bFIh5hp83zBndaaniCF1SBZWiA2vqWCJfIJKj1d38JQwydXnHfBtcSQjJTaob6x6lv2KjIXtwSmZTS2TMxTE02x1cJJ0FBDlT5ZIwUNEO6sTyjDrB2b8zQcpyrGKCe8U9NisiQ/3V8kHAGlzQSGM="

before_install:
  - env
  - locale
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem update cocoapods --no-rdoc --no-ri --no-document --quiet
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - ci/buildViaTravis.sh
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: "rm6J7g6QcEiwf4RZbLVGN/KJqmxmmu6PSmprSxliSeJdRsnnW4FECcGJ7sDKZEHR/YuLgAxP5TXMznI433ktPRhbWZcv56+GSJBDfXj4uPCwp7Ci/WpSxa8s+oeNfx0bzcwVVdKqQP9nQU8DwAjH/+t2MK+yJ/okOWS2sj9Wk45JQhjdIzMd1TE0XWsDyKjO68aSTuNlN6YI+1jxW09KfFyRq/GIytlWPKe430v6HZj5+mWtG4tc3nExC1XinqkFEJC+1zd21xu3yRgCGAQW9spyEZwxoJBkqMvIRLq6cdVvYK9SbeJIZfWcnkA7UmPzu4/ZHtcSYbPvCO83Vp11TUM/GgoQ3NKPqtf1waYblctR+5t0xDUzP85QnWOYE6FxI3SXgVWBtm6/KisY5I9fvoHlq/UO9BedPO0BwR8nOnKq5e4EOE4bCw/ylDzXuslgX6Fb5ugyRPd135bzkp55i//VgJnESoFkx5de5EHjQdZaWcdFFZAHI4yvOPHb1DTujOj9StcdTJQ0dvYBTTXUAEk9rfxKCq+eOZ9JvK9VqwH1waYR595qXV3Of+DC/kmnaQ2EWLN99+OFWTxvzha1ud3isT+VzkDDpFXcZlIXv7yA7Mm4E25ApWoqZxWqylYMPoz8hUR94t3p5UQX+1TsX+yCxKyKCE5xwW/QB4HYWRw="
