language: objective-c
osx_image: xcode10

addons:
  sonarcloud:
    organization: "guhungry-github"
    token:
      secure: "AQFFsLB8ZRtFo/zdfGrMWYHloilB1mU7jlJRVR0AnPxv/zH+q2ozZ0K0UEcRu7PJT2X0T386bsVLlfeXMZo4bHwdCqpVgqFo3PpQ+w51eW2vPdEAS2Hrj7h301YZQ1/AWrZaBsAn2XTJKvpZEprvQdTqQ/25pJz+udPyaigCifywB9EmoWDn3evEnYCW+ks90rGys/+Lwsaq35TmiUwetlAjUqgvpuM2pjJDxAW9Tyvdhbwqkh3aJFYELDOcCLkWzvq6F/NxVj5ssAbkHFJ6EMc38LS+nsNQmLv6ReaZxBNYAtiMDu/Ws3DfE0Wd/3KWovzkkF6ljs7tVjIu99mUgSBCLw1fuPgGie1y/DD0s0bqCk2gpbzJEOLveB30QF4/NslbTBE/mLhPe8H21Q42hm0WKuYewzVLy1M9HdICLE5imyO2rELRMzH99iG2/qr7qIBokgZ8lDCPYJIJ/zSi+6FaG5gl6b1JdFWJLPaPTomlgu6zmblddfyzDW/p0Z6fVJvdfhj6pU9U/q1U79eqIN9bFIh5hp83zBndaaniCF1SBZWiA2vqWCJfIJKj1d38JQwydXnHfBtcSQjJTaob6x6lv2KjIXtwSmZTS2TMxTE02x1cJJ0FBDlT5ZIwUNEO6sTyjDrB2b8zQcpyrGKCe8U9NisiQ/3V8kHAGlzQSGM="

before_install:
  - env
  - locale
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem update cocoapods --no-rdoc --no-ri --no-document --quiet
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - ci/buildViaTravis.sh
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: "XhDMnrP9cKaIZ1aEAJfJuwG0kzgvCKRNMyFc/8Mllvw/hj1cjWzKYBwOCqdqQzChu8lahVoAlNy6PfpVGYMEZ5agsw5GQ/xW+LRphkVIWOrHEUFUlXVEdReIZ0e7zH14oNGtbXnhPWNO2xJxpWSO0XwPz3uh3RHr9e2ZSX/fGBCWpRC2h3dl/KjIl8EmsDpRFw9m6hGYFwsRK18qGq99Z2nRYrqcET3IjuwoQiu+77/X8CPFMsrTjeXRQ2sJ382S9fDWeKkzJN93kX8Lxi9RT6b6ex+p18RTXIjubSxx0JBb5wXFxWzSXH/gy202TSV7w/StikPstLi2emKqc8AbYoHeaY7RBu0EOwS7c1Cfhdf5NIuYskcXVrOD5jl3B5DS+/LhbLoXUwr3AaG9t7Gh58SdQhPFsBOid80jtORvhNbmTW/TVNYL/Fgnkm980jySGqAz83tk56TBbuwP35qcbXyS/rfoIxlM/KvW3hPJPWzDAhVbvNXCnLljo74aPkEUNoL7nO4Em8KihMNu1gASMf72wLgQrYJ6Iqk2rpuDDL/iMFHXD0XltOJ+ydNGU8SO+T0vWMBg9iV3OOhKxlTOeeReoeLuerCe4skQHhz8qFOV0AhplupbhR6Mw309FqT9otC7kg5joax2aSs8WX5o4VLP8qbp76sCF7gK2uo4N3A="
