name: 'Build and Test'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Build and Test
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        shell: bash
        run: |
          xcodebuild clean test -scheme WCPhotoManipulator -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' -enableCodeCoverage YES -configuration Debug -derivedDataPath Build/ | xcpretty -c
          ./xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v8

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=guhungry-github
          -Dsonar.host.url=https://sonarcloud.io/
